name: Checkov
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:
  
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout repo
      uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb 
    - name: Super-Linter
      uses: github/super-linter/slim@01d3218744765b55c3b5ffbb27e50961e50c33c5

      
