name: Checkov
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:
  
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout repo
      uses: actions/checkout@master

    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@f93e43550d669f41ed6fcfa423a3fcb7484a36cd
