name: Checkov
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:
  
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout repo
      uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb 
    - name: Super-Linter
      uses: github/super-linter@v5.0.0

      
